export declare const EVENTS: {
    UPDATED_ADMINS: string;
    UPDATED_PLAYERS: string;
    UPDATED_SQUADS: string;
    PLAYER_TEAM_CHANGED: string;
    PLAYER_SQUAD_CHANGED: string;
    PLAYER_ROLE_CHANGED: string;
    PLAYER_LEADER_CHANGED: string;
    CHAT_COMMAND_SKIPMAP: string;
    ADMIN_BROADCAST: string;
    DEPLOYABLE_DAMAGED: string;
    NEW_GAME: string;
    PLAYER_CONNECTED: string;
    PLAYER_DISCONNECTED: string;
    PLAYER_DAMAGED: string;
    PLAYER_DIED: string;
    PLAYER_POSSESS: string;
    PLAYER_UNPOSSESS: string;
    PLAYER_REVIVED: string;
    PLAYER_SUICIDE: string;
    PLAYER_WOUNDED: string;
    ROUND_ENDED: string;
    ROUND_TICKETS: string;
    ROUND_WINNER: string;
    SQUAD_CREATED: string;
    VEHICLE_DAMAGED: string;
    TICK_RATE: string;
    CHAT_MESSAGE: string;
    POSSESSED_ADMIN_CAMERA: string;
    UNPOSSESSED_ADMIN_CAMERA: string;
    PLAYER_WARNED: string;
    PLAYER_KICKED: string;
    PLAYER_BANNED: string;
    LIST_PLAYERS: string;
    LIST_SQUADS: string;
    SHOW_CURRENT_MAP: string;
    SHOW_NEXT_MAP: string;
    SHOW_SERVER_INFO: string;
};
export declare const UPDATERS_REJECT_TIMEOUT = 10000;
export declare const UPDATE_TIMEOUT = 30000;
