import { LogsReaderEvents } from 'squad-logs';
import { RconEvents } from 'squad-rcon';

export const EVENTS = {
  ...RconEvents,
  ...LogsReaderEvents,
  UPDATED_ADMINS: 'UPDATED_ADMINS',
  UPDATED_PLAYERS: 'UPDATED_PLAYERS',
  UPDATED_SQUADS: 'UPDATED_SQUADS',
  PLAYER_TEAM_CHANGED: 'PLAYER_TEAM_CHANGED',
  PLAYER_SQUAD_CHANGED: 'PLAYER_SQUAD_CHANGED',
  PLAYER_ROLE_CHANGED: 'PLAYER_ROLE_CHANGED',
  PLAYER_LEADER_CHANGED: 'PLAYER_LEADER_CHANGED',

  // CHAT COMMANDS

  CHAT_COMMANDS_SKIPMAP: 'CHAT_COMMAND:skipmap',
  CHAT_COMMANDS_VOTEMAP: 'CHAT_COMMAND:votemap',
  CHAT_COMMANDS_ADMINS: 'CHAT_COMMAND:admins',
  CHAT_COMMANDS_REPORT: 'CHAT_COMMAND:report',
  CHAT_COMMANDS_R: 'CHAT_COMMAND:r',
  CHAT_COMMANDS_STVOL: 'CHAT_COMMAND:ствол',
  CHAT_COMMANDS_FIX: 'CHAT_COMMAND:fix',
};

export const UPDATERS_REJECT_TIMEOUT = 10000;
export const UPDATE_TIMEOUT = 30000;
